import { createApp } from "vue";
import "@/assets/css/style.css";
import App from "@/App.vue";
import pinia from "@/store";
import "@/utils/rem.ts";
import router from "@/router";
import "vant/lib/index.css";
import "vant/es/toast/style";
import { directives } from "@/utils/common";
import piniaPluginPersistedstate from "pinia-plugin-persistedstate";
pinia.use(piniaPluginPersistedstate);
const app = createApp(App);
directives(app);
app.use(pinia);
app.use(router);
app.mount("#app");
